### ISSUE TITLE
Project revamp

### ISSUE THREAD

**Issue by eddumelendez** [testcontainers/testcontainers-rs#563]
* Deprecate `cli` support
* Support [testcontainers/ryuk](https://hub.docker.com/r/testcontainers/ryuk) as resource reaper
* Read `tc.host` from `~/.testcontainers.properties` to connect with http client. See [issue](https://github.com/fussybeaver/bollard/issues/395) related to the docker client
* Add User-Agent with value `tc-rust/<version>`, version should be the [version from Cargo.toml](https://github.com/testcontainers/testcontainers-rs/blob/dev/testcontainers/Cargo.toml#L3)
```[tasklist]
### Tasks
- [x] Deprecate `cli` client support (provide sync version with http client under the hood)
- [x] Implement docker host configuration (including tc.host)
- [ ] https://github.com/testcontainers/testcontainers-rs/issues/576
- [ ] https://github.com/testcontainers/testcontainers-rs/issues/577
```

**Comment by DDtKey** [comment]
I've extracted separate issues for remaining tasks.
Main part is done within #575, so closing this issue and let's track new issues separately.
